---

- name: install package dependencies
  ansible.builtin.package: name={{ item }} state=present
  with_items:
    - python3
    - unzip

- name: check if aws_cli is installed
  ansible.builtin.stat:
    path: /usr/local/bin/aws
  changed_when: false
  register: aws_cli_stat

- name: install cni
  when: not aws_cli_stat.stat.exists
  block:
    - name: download the awscli archive
      ansible.builtin.get_url:
        url: "{{ aws_cli_archive }}"
        dest: /tmp/awscli.zip
        mode: "0644"

    - name: unarchive the installer
      ansible.builtin.unarchive: src=/tmp/awscli.zip dest=/tmp copy=no

    - name: install awscli package
      ansible.builtin.shell: /tmp/aws/install
      args:
        chdir: /tmp/aws
        executable: /bin/sh

    - name: link aws cli
      ansible.builtin.file:
        src: /usr/local/bin/aws
        dest: /usr/bin/aws
        owner: root
        group: root
        state: link

    - name: clean up
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/awscli.zip
        - /tmp/aws
